<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.service_locator.vg8qKPi' shared service.

return $this->privates['.service_locator.vg8qKPi'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($this->getService, [
    'comptePartenaireRepository' => ['privates', 'App\\Repository\\ComptePartenaireRepository', 'getComptePartenaireRepositoryService.php', true],
], [
    'comptePartenaireRepository' => 'App\\Repository\\ComptePartenaireRepository',
]);
