<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.service_locator.kfbCA7i' shared service.

return $this->privates['.service_locator.kfbCA7i'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($this->getService, [
    'utilisateur' => ['privates', '.errored..service_locator.kfbCA7i.App\\Entity\\Utilisateur', NULL, 'Cannot autowire service ".service_locator.kfbCA7i": it references class "App\\Entity\\Utilisateur" but no such service exists.'],
], [
    'utilisateur' => 'App\\Entity\\Utilisateur',
]);
