<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.service_locator.Dqh887e' shared service.

return $this->privates['.service_locator.Dqh887e'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($this->getService, [
    'utilisateurRepository' => ['privates', 'App\\Repository\\UtilisateurRepository', 'getUtilisateurRepositoryService.php', true],
], [
    'utilisateurRepository' => 'App\\Repository\\UtilisateurRepository',
]);
