<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.service_locator.Fsg2.hi' shared service.

return $this->privates['.service_locator.Fsg2.hi'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($this->getService, [
    'authentificationRepository' => ['privates', 'App\\Repository\\AuthentificationRepository', 'getAuthentificationRepositoryService.php', true],
], [
    'authentificationRepository' => 'App\\Repository\\AuthentificationRepository',
]);
