<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.service_locator.L2gSbzR' shared service.

return $this->privates['.service_locator.L2gSbzR'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($this->getService, [
    'comptePartenaire' => ['privates', '.errored..service_locator.L2gSbzR.App\\Entity\\ComptePartenaire', NULL, 'Cannot autowire service ".service_locator.L2gSbzR": it references class "App\\Entity\\ComptePartenaire" but no such service exists.'],
], [
    'comptePartenaire' => 'App\\Entity\\ComptePartenaire',
]);
